### PR TITLE
LRDOCS-3934 Tutorial: Blacklisting OSGi Modules

### PR DESCRIPTION
**Pull request by jhinkey**
Here's the draft, Matthew. Thanks for reviewing!

### CODE REVIEW

**Comment by mtambara** [comment]
@jhinkey It looks good right now, but we're still making some changes that could affect the doc contents. I'll ping you again when we send Brian the final pull

**Comment by jhinkey** [comment]
@mtambara Matthew, any more changes to the feature? If not, do you approve the doc?

Also, what Fix Pack is this going into?
Thanks

**Comment by mtambara** [comment]
@jhinkey One of the changes we made was that removing the configuration file will also reinstall all blacklisted bundles. This change has been added to the ticket (https://issues.liferay.com/browse/LPS-73562). Would you be able to update and send me the new doc? Thanks!

**Comment by jhinkey** [comment]
Gotcha, @mtambara . I'll update the doc with that.

**Pull request closed without merging**
